<?php

declare(strict_types=1);

/** Gerado em 2026-05-20T12:08:09+00:00 — não edite à mão */
return array (
  0 => 'aumentar-recompra-ecommerce',
  1 => 'aumentar-ticket-medio-ecommerce-sem-mais-trafego',
  2 => 'calcular-cac-ecommerce',
  3 => 'como-parar-de-depender-de-anuncios',
  4 => 'como-saber-se-ecommerce-esta-pronto-para-escalar',
  5 => 'como-saber-se-trafego-pago-funciona-ecommerce',
  6 => 'ecommerce-pequeno-competir-grandes-marcas',
  7 => 'email-marketing-ecommerce',
  8 => 'erros-checkout-ecommerce',
  9 => 'escolher-produtos-para-anunciar-ecommerce',
  10 => 'frete-gratis-ecommerce-margem',
  11 => 'google-ads-ou-meta-ads-ecommerce',
  12 => 'ltv-ecommerce',
  13 => 'marketplace-ou-ecommerce-proprio',
  14 => 'melhorar-conversao-loja-online',
  15 => 'melhorar-pagina-produto-ecommerce',
  16 => 'metricas-ecommerce',
  17 => 'o-que-faz-ecommerce-crescer-de-verdade',
  18 => 'por-que-ecommerce-recebe-visitas-mas-nao-vende',
  19 => 'por-que-ecommerce-vende-pouco-investindo-em-anuncios',
  20 => 'quanto-custa-vender-online-lucro-real-ecommerce',
  21 => 'quanto-investir-trafego-ecommerce',
  22 => 'reduzir-abandono-carrinho-ecommerce',
  23 => 'roas-bom-ecommerce-nao-cresce',
  24 => 'roas-ruim-como-diagnosticar-ecommerce',
  25 => 'seo-ecommerce',
  26 => 'site-lento-afeta-vendas-ecommerce',
  27 => 'taxa-conversao-ecommerce',
  28 => 'trafego-pago-ecommerce',
  29 => 'vale-investir-google-shopping-ecommerce',
  30 => 'vale-pena-contratar-agencia-trafego-ecommerce',
  31 => 'vender-mais-whatsapp-ecommerce',
  32 => '12-gargalos-crescimento-ecommerce',
  33 => 'agencia-ecommerce-vale-a-pena',
  34 => 'checklist-ecommerce-saudavel-25-sinais',
  35 => 'descobrir-gargalo-antes-investir-anuncios',
  36 => 'diagnosticar-ecommerce-nao-cresce',
  37 => 'ecommerce-nao-escala-com-mais-orcamento',
  38 => 'ecommerce-nao-vende-trafego-site-oferta',
  39 => 'google-ads-ecommerce-funciona-diagnostico',
  40 => 'quanto-investir-ecommerce-escalar',
  41 => 'vale-a-pena-trafego-pago-ecommerce-faturamento',
);
