<?php

declare(strict_types=1);

/**
 * Restaura acentuação comum nos lotes 11–20 (gerados sem UTF-8 completo).
 * Uso: php scripts/fix-blog-articles-utf8.php
 */

$files = [
    __DIR__ . '/blog-articles/articles-11-15.php',
    __DIR__ . '/blog-articles/articles-16-20.php',
];

$map = [
    'acoes' => 'ações',
    'acao' => 'ação',
    'operacoes' => 'operações',
    'operacao' => 'operação',
    'conversao' => 'conversão',
    'informacao' => 'informação',
    'informacoes' => 'informações',
    'decisao' => 'decisão',
    'decisoes' => 'decisões',
    'confianca' => 'confiança',
    'cartao' => 'cartão',
    'pagamentos' => 'pagamentos',
    'avaliacao' => 'avaliação',
    'avaliacoes' => 'avaliações',
    'recomendacao' => 'recomendação',
    'recomendacoes' => 'recomendações',
    'recuperacao' => 'recuperação',
    'segmentacao' => 'segmentação',
    'otimizacao' => 'otimização',
    'automacao' => 'automação',
    'automacoes' => 'automações',
    'comunicacao' => 'comunicação',
    'negociacao' => 'negociação',
    'reposicao' => 'reposição',
    'devolucao' => 'devolução',
    'devolucoes' => 'devoluções',
    'atencao' => 'atenção',
    'intencao' => 'intenção',
    'percepcao' => 'percepção',
    'situacao' => 'situação',
    'condicao' => 'condição',
    'condicoes' => 'condições',
    'promocao' => 'promoção',
    'promocoes' => 'promoções',
    'variacao' => 'variação',
    'variacoes' => 'variações',
    'disponibilidade' => 'disponibilidade',
    'competicao' => 'competição',
    'escalacao' => 'escalação',
    'aquisicao' => 'aquisição',
    'contribuicao' => 'contribuição',
    'rentabilidade' => 'rentabilidade',
    'lucratividade' => 'lucratividade',
    'margem' => 'margem',
    'historico' => 'histórico',
    'metrica' => 'métrica',
    'metricas' => 'métricas',
    'diagnostico' => 'diagnóstico',
    'diagnosticos' => 'diagnósticos',
    'criterio' => 'critério',
    'criterios' => 'critérios',
    'analise' => 'análise',
    'analises' => 'análises',
    'estrategia' => 'estratégia',
    'estrategias' => 'estratégias',
    'tecnica' => 'técnica',
    'tecnicas' => 'técnicas',
    'pratica' => 'prática',
    'praticas' => 'práticas',
    'publico' => 'público',
    'publicos' => 'públicos',
    'preco' => 'preço',
    'precos' => 'preços',
    'orcamento' => 'orçamento',
    'orcamentos' => 'orçamentos',
    'numero' => 'número',
    'numeros' => 'números',
    'periodo' => 'período',
    'periodos' => 'períodos',
    'medio' => 'médio',
    'media' => 'média',
    'medios' => 'médios',
    'rapido' => 'rápido',
    'rapida' => 'rápida',
    'rapidos' => 'rápidos',
    'lentidao' => 'lentidão',
    'velocidade' => 'velocidade',
    'pagina' => 'página',
    'paginas' => 'páginas',
    'titulo' => 'título',
    'titulos' => 'títulos',
    'descricao' => 'descrição',
    'descricoes' => 'descrições',
    'categoria' => 'categoria',
    'categorias' => 'categorias',
    'transmissao' => 'transmissão',
    'pos-compra' => 'pós-compra',
    'pos-venda' => 'pós-venda',
    'pre-compra' => 'pré-compra',
    'reacao' => 'reação',
    'experiencia' => 'experiência',
    'necessario' => 'necessário',
    'necessaria' => 'necessária',
    'necessarios' => 'necessários',
    'possivel' => 'possível',
    'impossivel' => 'impossível',
    'util' => 'útil',
    'uteis' => 'úteis',
    'ja ' => 'já ',
    'ate ' => 'até ',
    'tambem' => 'também',
    'nao ' => 'não ',
    ' nao' => ' não',
    'nao.' => 'não.',
    'nao,' => 'não,',
    'nao?' => 'não?',
    'nao;' => 'não;',
    'nao:' => 'não:',
    ' e um' => ' é um',
    ' e uma' => ' é uma',
    ' e o' => ' é o',
    ' e a' => ' é a',
    ' e quando' => ' é quando',
    ' e que' => ' é que',
    ' e por' => ' é por',
    ' e mais' => ' é mais',
    ' e o ' => ' é o ',
    ' e a ' => ' é a ',
    ' e um ' => ' é um ',
    ' e uma ' => ' é uma ',
    ' so ' => ' só ',
    'apos ' => 'após ',
    ' apos ' => ' após ',
    'alem ' => 'além ',
    ' alem ' => ' além ',
    'entao ' => 'então ',
    ' entao ' => ' então ',
    'voce ' => 'você ',
    ' voce ' => ' você ',
    'Voce ' => 'Você ',
    'sera ' => 'será ',
    ' sera ' => ' será ',
    'esta ' => 'está ',
    ' esta ' => ' está ',
    'estao ' => 'estão ',
    ' estao ' => ' estão ',
    'sao ' => 'são ',
    ' sao ' => ' são ',
    'ha ' => 'há ',
    ' ha ' => ' há ',
    'proximo' => 'próximo',
    'proxima' => 'próxima',
    'proximos' => 'próximos',
    'facil' => 'fácil',
    'faceis' => 'fáceis',
    'dificil' => 'difícil',
    'dificuldade' => 'dificuldade',
    'especifico' => 'específico',
    'especifica' => 'específica',
    'especificos' => 'específicos',
    'generico' => 'genérico',
    'generica' => 'genérica',
    'unico' => 'único',
    'unica' => 'única',
    'unicos' => 'únicos',
    'basico' => 'básico',
    'basica' => 'básica',
    'minimo' => 'mínimo',
    'minima' => 'mínima',
    'maximo' => 'máximo',
    'maxima' => 'máxima',
    'logica' => 'lógica',
    'logico' => 'lógico',
    'economico' => 'econômico',
    'economica' => 'econômica',
    'financeiro' => 'financeiro',
    'financeira' => 'financeira',
    'comercial' => 'comercial',
    'profissional' => 'profissional',
    'tecnologico' => 'tecnológico',
    'automatico' => 'automático',
    'automatica' => 'automática',
    'involuntario' => 'invasivo',
    'invasiva' => 'invasiva',
    'invasivos' => 'invasivos',
    'invasivo' => 'invasivo',
    'agressivo' => 'agressivo',
    'agressiva' => 'agressiva',
    'consultivo' => 'consultivo',
    'consultiva' => 'consultiva',
    'objetivo' => 'objetivo',
    'objetiva' => 'objetiva',
    'clareza' => 'clareza',
    'prioridade' => 'prioridade',
    'prioridades' => 'prioridades',
    'relevancia' => 'relevância',
    'relevante' => 'relevante',
    'relevantes' => 'relevantes',
    'frequencia' => 'frequência',
    'sequencia' => 'sequência',
    'mensagem' => 'mensagem',
    'mensagens' => 'mensagens',
    'abordagem' => 'abordagem',
    'abordagens' => 'abordagens',
    'comparacao' => 'comparação',
    'comparacoes' => 'comparações',
    'comparativo' => 'comparativo',
    'comparativa' => 'comparativa',
    'concorrente' => 'concorrente',
    'concorrentes' => 'concorrentes',
    'concorrencia' => 'concorrência',
    'mercado' => 'mercado',
    'cenario' => 'cenário',
    'cenarios' => 'cenários',
    'exemplo' => 'exemplo',
    'exemplos' => 'exemplos',
    'resultado' => 'resultado',
    'resultados' => 'resultados',
    'indicador' => 'indicador',
    'indicadores' => 'indicadores',
    'problema' => 'problema',
    'problemas' => 'problemas',
    'solucao' => 'solução',
    'solucoes' => 'soluções',
    'processo' => 'processo',
    'processos' => 'processos',
    'produto' => 'produto',
    'produtos' => 'produtos',
    'servico' => 'serviço',
    'servicos' => 'serviços',
    'cliente' => 'cliente',
    'clientes' => 'clientes',
    'compra' => 'compra',
    'compras' => 'compras',
    'venda' => 'venda',
    'vendas' => 'vendas',
    'pedido' => 'pedido',
    'pedidos' => 'pedidos',
    'carrinho' => 'carrinho',
    'carrinhos' => 'carrinhos',
    'checkout' => 'checkout',
    'frete' => 'frete',
    'fretes' => 'fretes',
    'entrega' => 'entrega',
    'entregas' => 'entregas',
    'estoque' => 'estoque',
    'estoques' => 'estoques',
    'campanha' => 'campanha',
    'campanhas' => 'campanhas',
    'anuncio' => 'anúncio',
    'anuncios' => 'anúncios',
    'trafego' => 'tráfego',
    'midia' => 'mídia',
    'criativo' => 'criativo',
    'criativos' => 'criativos',
    'plataforma' => 'plataforma',
    'plataformas' => 'plataformas',
    'relatorio' => 'relatório',
    'relatorios' => 'relatórios',
    'relatorio' => 'relatório',
];

// Ordenar por tamanho decrescente para evitar substituições parciais
uksort($map, static fn ($a, $b) => strlen($b) <=> strlen($a));

foreach ($files as $file) {
    if (!is_file($file)) {
        echo "Arquivo não encontrado: {$file}\n";
        continue;
    }
    $content = file_get_contents($file);
    if ($content === false) {
        continue;
    }
    $original = $content;
    foreach ($map as $from => $to) {
        $content = str_replace($from, $to, $content);
    }
    if ($content !== $original) {
        file_put_contents($file, $content);
        echo "Atualizado: {$file}\n";
    } else {
        echo "Sem alteração: {$file}\n";
    }
}

echo "Concluído.\n";
